[tool.poetry]
name = "bank-operation"
version = "0.1.0"
description = ""
authors = ["Roman <sqrap@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
python-dotenv = "^1.1.0"
requests = "^2.32.3"
pandas = "^2.2.3"
urllib3 = "^2.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310']

[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["flask", "django"]

[tool.mypy]
files = "src"
ignore_missing_imports = true
